apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "itscout.fullname" . }}
data:
  DB_USER: "{{ .Values.postgres.DB_USER }}"
  DB_NAME: "itscout"
  DB_PORT: "{{ .Values.postgres.service.port }}"
  DB_HOSTNAME: "{{ template "postgres.fullname" .Subcharts.postgres }}"
