apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "itscout.fullname" . }}
  labels:
    {{- include "itscout.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "itscout.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "itscout.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "itscout.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: {{ include "itscout.fullname" . }}
                key: DB_USER
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ include "itscout.fullname" . }}
                key: DB_NAME
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "itscout.fullname" . }}
                key: DB_PORT
          - name: DB_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ include "itscout.fullname" . }}
                key: DB_HOSTNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ template "postgres.fullname" .Subcharts.postgres }}"
                key: pgPasswd
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
